function nirsHSJ
% Based on spm_vbm8 from vbm8
% Toolbox wrapper to call mctools functions

rev = '$Rev: 1 $';

SPMid = spm('FnBanner',mfilename,rev);
[Finter,Fgraph,CmdLine] = spm('FnUIsetup','NIRSHSJ');
spm_help('!ContextHelp',mfilename);
spm_help('!Disp','nirsHSJ.man','',Fgraph,'NIRSHSJ');

fig = spm_figure('GetWin','Interactive');
h0  = uimenu(fig,...
    'Label',	'nirsHSJ',...
    'Separator',	'on',...
    'Tag',		'NIRS',...
    'HandleVisibility','on');

h1  = uimenu(h0,...
	'Label',	'Read NIRS data',...
	'Separator',	'on',...
	'Tag',		'Read NIRS data',...
	'HandleVisibility','on');
h11  = uimenu(h1,...
        'Label',	'Read BOXY data',...
        'Separator',	'off',...
        'Tag',		'Read BOXY data',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.nirsHSJ.readNIRS.boxy1'');',...
        'HandleVisibility','on');
    
h2  = uimenu(h0,...
	'Label',	'Artefact Detection',...
	'Separator',	'off',...
	'Tag',		'Artefact Detection',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.nirsHSJ.artefactdetection'');',...
	'HandleVisibility','on');
    h21  = uimenu(h2,...
            'Label',	'Step detection',...
            'Separator',	'off',...
            'Tag',		'stepdetection',...
            'CallBack','spm_jobman(''interactive'','''',''spm.tools.nirsHSJ.artefactdetection.stepdetection'');',...
            'HandleVisibility','on');
    h22  = uimenu(h2,...
            'Label',	'Normalize data',...
            'Separator',	'off',...
            'Tag',		'norm',...
            'CallBack','spm_jobman(''interactive'','''',''spm.tools.nirsHSJ.artefactdetection.E_findcorr'');',...
            'HandleVisibility','on');

h3  = uimenu(h0,...
	'Label',	'Preprocess NIRS data',...
	'Separator',	'on',...
	'Tag',		'Preprocess NIRS data',...
	'HandleVisibility','on');
    h31  = uimenu(h3,...
        'Label',	'Normalize data',...
        'Separator',	'off',...
        'Tag',		'norm',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.nirsHSJ.E_normalization'');',...
        'HandleVisibility','on');
    h32  = uimenu(h3,...
        'Label',	'Nullify bad intervals',...
        'Separator',	'off',...
        'Tag',		'nullify',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.nirsHSJ.nullifybad'');',...
        'HandleVisibility','on');
    h33  = uimenu(h3,...
        'Label',	'Fast preprocess',...
        'Separator',	'off',...
        'Tag',		'fastpre',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.nirsHSJ.preprocess'');',...
        'HandleVisibility','on');
    h34  = uimenu(h3,...
        'Label',	'Bandpass filtering',...
        'Separator',	'off',...
        'Tag',		'bandpassfilt',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.nirsHSJ.E_filter'');',...
        'HandleVisibility','on');
    h35  = uimenu(h3,...
        'Label',	'ConvertODtoHb',...
        'Separator',	'off',...
        'Tag',		'convertODtoHb',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.nirsHSJ.ODtoHbOHbR'');',...
        'HandleVisibility','on');
    
h4  = uimenu(h0,...
	'Label',	'Process NIRS data',...
	'Separator',	'on',...
	'Tag',		'Process NIRS data',...
	'HandleVisibility','on');
    h41  = uimenu(h4,...
        'Label',	'Average',...
        'Separator',	'off',...
        'Tag',		'Average',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.nirsHSJ.dataprocessing.average'');',...
        'HandleVisibility','on');
    h42  = uimenu(h4,...
        'Label',	'PCA',...
        'Separator',	'off',...
        'Tag',		'PCA',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.nirsHSJ.dataprocessing.PCA'');',...
        'HandleVisibility','on');
    
h5 = uimenu(h0,...
	'Label',	'WriteNIRS',...
	'Separator',	'on',...
	'Tag',		'WriteNIRS',...
	'HandleVisibility','on');
    h51 = uimenu(h5,...
        'Label',	'WriteNIRS',...
        'Separator',	'off',...
        'Tag',		'WriteNIRS',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.nirsHSJ.datawriteNIRS.writeNIRS'');',...
        'HandleVisibility','on');
    
h6 = uimenu(h0,...
	'Label',	'ShowGUI',...
	'Separator',	'on',...
	'Tag',		'ShowGUI',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.nirsHSJ.GUI.E_GUI'');',...
	'HandleVisibility','on');

h7 = uimenu(h0,...
	'Label',	'ShowGUI',...
	'Separator',	'on',...
	'Tag',		'ShowGUI',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.nirsHSJ.GUI.E_GUI'');',...
	'HandleVisibility','on');
