function nirs_run_E_GUI_lookmatrices(job)
% Lunch IOMtg program
GUI_LookMatrices;
sprintf(['Open the GUI_LookMatrices GUI, you could also just write: GUI_LookMatrice in the command window to open it,\n', ...
    'This GUI is used to visualize matrices according to the zone defined in the DisplayGUI, it helps to visualize and  \n',...
    'organize the result in a meaningful way. To open the matrices you must create an Excel to list the one you like to visualized as follows: \n' ...
    'First column: path of the matrice, Second column: name of the matrice subject1.mat, Third column: Zone file to identify the channel organization 8ROI.zone,\n',...
    'Fourth column: group identification used for statistics, Fifth and other are optional to visualize covariable' ])