function Install()

    rep = pwd;
    IOMtgSettings.InstallationRepertory = rep;
        
    fid_IOMtg = fopen('IOMtg.m', 'wt');
    
    path_Root        = rep;
    path_Classes     = fullfile(  rep, 'IO_Classes' );
    path_Dialogs     = fullfile(  rep, 'IO_Dialogs' );
    path_FileFuncs   = fullfile(  rep, 'IO_FileFuncs' );
    path_UtilFuncs   = fullfile(  rep, 'IO_UtilFuncs' );
    path_Icons       = fullfile(  rep, 'IO_Icons' );
    path_Rendering   = fullfile(  rep, 'IO_Rendering' );
    path_Help        = fullfile(  rep, 'IO_Help' );
    
    fprintf(fid_IOMtg, '%%This file is automatically Generated by Install.m\n');
    fprintf(fid_IOMtg, 'function IOMtg(args)\n');
    fprintf(fid_IOMtg, '\n');
    fprintf(fid_IOMtg, '    clear classes;\n');
    fprintf(fid_IOMtg, '\n');
    fprintf(fid_IOMtg, '    %%Note: Paths defined in Install.m\n');
    fprintf(fid_IOMtg, '\n');
    fprintf(fid_IOMtg, '    addpath( ''%s'' );\n', path_Root );
    fprintf(fid_IOMtg, '    addpath( ''%s'' );\n', path_Classes );
    fprintf(fid_IOMtg, '    addpath( ''%s'' );\n', path_Dialogs );
    fprintf(fid_IOMtg, '    addpath( ''%s'' );\n', path_FileFuncs );
    fprintf(fid_IOMtg, '    addpath( ''%s'' );\n', path_UtilFuncs );
    fprintf(fid_IOMtg, '    addpath( ''%s'' );\n', path_Icons );
    fprintf(fid_IOMtg, '    addpath( ''%s'' );\n', path_Rendering );
    fprintf(fid_IOMtg, '    addpath( ''%s'' );\n', path_Help );
    fprintf(fid_IOMtg, '\n');
    fprintf(fid_IOMtg, '    save path;\n');
    fprintf(fid_IOMtg, '\n');
    fprintf(fid_IOMtg, '    %%Launches IOMtg Main Window\n');
    fprintf(fid_IOMtg, '    IO_Dlg_MainWindow()\n');
    fprintf(fid_IOMtg, '\n');
    
    disp(' ');
    disp(' ');
    disp(' ');
    disp('     File ''IOMtg.m'' Created');
    disp( sprintf('     Installation directory : %s', rep ) );
    disp('     IOMtg installation Complete. Type IOMtg to start the application.' );
    disp(' ');
    
    fclose(fid_IOMtg);
    
    IOMtg;