%This file is automatically Generated by Install.m
function IOMtg(args)

%    clear classes;

    %Note: Paths defined in Install.m

%     addpath( 'D:\Mes documents on Julie\hiv2007\IOMtg_14Mai_2008' );
%     addpath( 'D:\Mes documents on Julie\hiv2007\IOMtg_14Mai_2008\IO_Classes' );
%     addpath( 'D:\Mes documents on Julie\hiv2007\IOMtg_14Mai_2008\IO_Dialogs' );
%     addpath( 'D:\Mes documents on Julie\hiv2007\IOMtg_14Mai_2008\IO_FileFuncs' );
%     addpath( 'D:\Mes documents on Julie\hiv2007\IOMtg_14Mai_2008\IO_UtilFuncs' );
%     addpath( 'D:\Mes documents on Julie\hiv2007\IOMtg_14Mai_2008\IO_Icons' );
%     addpath( 'D:\Mes documents on Julie\hiv2007\IOMtg_14Mai_2008\IO_Rendering' );
%     addpath( 'D:\Mes documents on Julie\hiv2007\IOMtg_14Mai_2008\IO_Help' );
% 
%     save path;

    %Launches IOMtg Main Window
    IO_Dlg_MainWindow()

